name: dsml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pytest=7.4.4
  - pytest-cov=4.1.0
  - ruff=0.11.2
  - numpy=2.1.0
  - pandas=2.2.2
  - seaborn=0.13.2
  - jupyter=1.0.0
